import type { Metadata } from 'next';
import { SessionProvider } from 'next-auth/react';

import { Toaster } from '@/components/ui/sonner';

import './globals.css';

import { auth } from '@/auth';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  return (
    <html lang='en' suppressHydrationWarning className='dark h-full'>
      <body suppressHydrationWarning className='h-full'>
        <SessionProvider session={session}>
          <main className='flex-1 w-full'>{children}</main>
          <Toaster />
        </SessionProvider>
      </body>
    </html>
  );
}
